# Generated by Django 6.0 on 2026-02-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_order_payment_receipt_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Tayyorlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20),
        ),
    ]
