# Generated by Django 6.0 on 2026-02-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
