# Generated by Django 6.0 on 2026-03-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_order_location_latitude_order_location_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
    ]
