# Generated by Django 6.0 on 2026-03-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_dish_image_remove_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='', upload_to='dishes/'),
            preserve_default=False,
        ),
    ]
